### ISSUE TITLE
Add information about used Node versions

### ISSUE THREAD

**Issue by rajbos** [rajbos/actions-marketplace-checks#11]
Pick it up from the `action.yml` file in the root of the repo and add it to the report

``` yaml
runs:
  using: 'node16'
  main: 'dist/main.js'
```
